### ISSUE TITLE
起動するたびにPixelsのScriptableObjectをアタッチしなければいけない問題

### ISSUE THREAD

**Issue by 8picomu** [8picomu/Matomaru#3]

**Comment by pf35301** [comment]
中身がシリアライズされていない？

**Comment by pf35301** [comment]
ScriptableObjectsを作るときにListWrapper作って多次元配列を無理やりシリアライズしようとするとUnity Editorを再起動するたびにScriptableObjectの実態が壊れて読み込まれなる

**Comment by 8picomu** [comment]
![image](https://user-images.githubusercontent.com/18531809/108442815-0ab40780-729b-11eb-9e1e-20a478b75341.png)
緊急の対応としてはPixelEditorを開き、
![image](https://user-images.githubusercontent.com/18531809/108442884-2b7c5d00-729b-11eb-9d15-cb2fa029cbcc.png)
XSizeとYSizeを指定して`Recreate CanvasData`を押し、
![image](https://user-images.githubusercontent.com/18531809/108442938-3fc05a00-729b-11eb-9f00-8a57e3c71ab7.png)
`Create ScriptableObject`を押し、
![image](https://user-images.githubusercontent.com/18531809/108442991-536bc080-729b-11eb-88c7-a68336930dad.png)
生成されたScriptableObjectを
![image](https://user-images.githubusercontent.com/18531809/108443063-78f8ca00-729b-11eb-9bb1-c13042d7160d.png)
Target_ECSのPixelsの
![image](https://user-images.githubusercontent.com/18531809/108443100-857d2280-729b-11eb-8b6f-205f54619680.png)
Canvas Dataに当てると動かすことができる

**Comment by 8picomu** [comment]
List<Wrapper>でWrapperにbool[]をもたせる組み合わせのみうまくシリアライズされる？

**Comment by 8picomu** [comment]
ScriptableObjectの中身がメンバ変数ではなくプロパティになっていただけだった
